baseURL = 'https://lachlancook.com'
languageCode = 'en-us'
title = 'Lachlan Cook'
theme = 'PaperMod'

[author]
    name = 'Lachlan Cook'

[params]
    author = 'Lachlan Cook'
    math = true

[taxonomies]
    category = 'categories'
    tag = 'tags'

[menu]
  [[menu.main]]
    name = "Physics"
    url = "/categories/physics/"
    weight = 1

  [[menu.main]]
    name = "Mathematics"
    url = "/categories/mathematics/"
    weight = 2

  [[menu.main]]
    name = "Programming"
    url = "/categories/programming/"
    weight = 3
